### ISSUE TITLE
How can I check Bluetooth On/Off State?

### ISSUE THREAD

**Issue by JAICHANGPARK** [edufolly/flutter_bluetooth_serial#30] opened 2019-05-28 02:58 UTC
I'd like to check Bluetooth On/Off State before connection 

Can I check this?

**Comment by FWeissenb** [comment] 2019-05-29 15:35
There is an "isOn" 

Should be something like (untested)

```
var isOn = await FlutterBluetoothSerial.instance.isOn;

if(isOn) {
//TODO
}
````

**Comment by PsychoXIVI** [comment] 2019-05-30 11:22
In few days there might be: See #35

**Comment by PsychoXIVI** [comment] 2019-06-18 19:16
The pull request #35 will be merged soon, and it adds the option, so the issue is being closed. 
And there is syntax:
```Dart
// Single call check
bool isEnabled = await FlutterBluetoothSerial.instance.isEnabled;

// Or listening for changes
FlutterBluetoothSerial.instance.onStateChanged().listen((BluetoothState state) {
    // The `BluetoothState` has enum-like interface with `isEnabled` getter (true if `state == BluetoothState.STATE_ON` 
    print(state.isEnabled); 
});
```

**Closed by PsychoXIVI** 2019-06-18 19:16 UTC
Labels: enhancement, question
