### ISSUE TITLE
Example not working while connecting to a device in Chat Page

### ISSUE THREAD

**Issue by anil-sookshum** [edufolly/flutter_bluetooth_serial#80] opened 2019-12-23 07:43 UTC
I am getting the following issue while connecting to start chat i.e issue on the Chat page.
```
I/flutter (20943): Cannot connect, exception occured                    
I/flutter (20943): Connect -> selected C0:EE:FB:53:44:3D                
I/flutter (20943): PlatformException(connect_error, read failed, socket might closed or timeout, read ret: -1, java.io.IOException: read failed, socket might closed or timeout, read ret: -1
I/flutter (20943):      at android.bluetooth.BluetoothSocket.readAll(BluetoothSocket.java:762)
I/flutter (20943):      at android.bluetooth.BluetoothSocket.readInt(BluetoothSocket.java:776)
I/flutter (20943):      at android.bluetooth.BluetoothSocket.connect(BluetoothSocket.java:399)
I/flutter (20943):      at io.github.edufolly.flutterbluetoothserial.BluetoothConnection.connect(BluetoothConnection.java:57)
I/flutter (20943):      at io.github.edufolly.flutterbluetoothserial.BluetoothConnection.connect(BluetoothConnection.java:64)
I/flutter (20943):      at io.github.edufolly.flutterbluetoothserial.FlutterBluetoothSerialPlugin.lambda$onMethodCall$0(FlutterBluetoothSerialPlugin.java:880)
I/flutter (20943):      at io.github.edufolly.flutterbluetoothserial.-$$Lambda$FlutterBluetoothSerialPlugin$ysyByl051NlOhDx-4TeZKtqb1pA.run(Unknown Source:10)
I/flutter (20943):      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
I/flutter (20943):      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
I/flutter (20943):      at java                                         
I/flutter (20943): Cannot connect, exception occured
```

**Comment by PsychoXIVI** [comment] 2019-12-24 19:59
Duplicate of #18. Please double all things mentioned in [my comment](https://github.com/edufolly/flutter_bluetooth_serial/issues/18#issuecomment-506472861).

**Closed by PsychoXIVI** 2019-12-24 19:59 UTC
